/**
 * THIS FILE IS AUTO-GENERATED - DO NOT EDIT DIRECTLY
 * -----------------------------------------------
 * Generated by the DI generator script.
 *
 * To add new injectable classes, use the @injectable decorator from src/platform/common/di/injectable.ts
 * Example: @injectable('MyServiceId', 'Singleton')
 *
 * Run 'npm run generate-di' to regenerate this file after adding new injectable classes.
 */
import { Container } from 'inversify';
import getContainer, { registerModule } from '../core/di/registry';

let container: Container;
const provider = {
  async get<T>(id: string): Promise<T> {
    if (!container) {
      // Configure container based on environment
      // Create an array to hold all modules
      const modules: any[] = [];

      // Add environment-specific modules
      if (typeof window === 'undefined') {
        // Server-side modules
        modules.push(await import('./hello/impl/UserAgentServiceServer'));
      } else {
        // Client-side modules
        modules.push(await import('./hello/impl/UserAgentServiceClient'));
      }

      // Add common modules for both client and server
      modules.push(
        await import('./product/impl/EmporixProductService'),
        await import('./model/product/impl/EmporixProductMapper'),
        await import('./hello/impl/HelloAgentService'),
      );

      // Register all modules
      for (const m of modules) {
        registerModule(m, 'service');
      }
      // Initialize container
      container = await getContainer('service');
    }
    return container.get<T>(id);
  },
};
export default provider;
